### ISSUE TITLE
FarmAnimal one word in Question URL?

### ISSUE THREAD

**Issue by gopperman** [BostonGlobe/elections-2016#316] opened 2016-10-27 18:15 UTC
http://localhost:3001/elections/2016/race/Question/3%2520-%2520Improve%2520FarmAnimal%2520Confines

**Comment by gopperman** [comment] 2016-10-27 18:15
Also in descriptions and titles

**Comment by gabrielflorit** [comment] 2016-10-27 20:42
duplicate of https://github.com/BostonGlobe/elections-2016/issues/318

**Closed by gabrielflorit** 2016-10-27 20:42 UTC
Labels: typos
